"""Tests for the artwork validation engine."""
import pytest

from packaging_model.models import (
    Product,
    Strength,
    Manufacturer,
    BlisterSpec,
    PackagingConfig,
    ArtworkSpec,
    TextElement,
    BarcodeElement,
    CodingZone,
    SpotColor,
)
from packaging_model.enums import (
    DosageForm,
    PanelType,
    BarcodeType,
    ArtworkStatus,
)
from artwork_engine.text_layout import generate_default_artwork
from validation_engine import (
    CheckStatus,
    Severity,
    ValidationResult,
    check_completeness,
    compare_text,
    compare_revisions,
    validate_barcodes,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_product(**overrides) -> Product:
    defaults = dict(
        id="TEST-500",
        brand_name="AZICURE",
        generic_name="Azithromycin",
        strength=Strength(value=500, unit="mg"),
        dosage_form=DosageForm.TABLET,
        composition="Each tablet contains: Azithromycin IP 500 mg",
        manufacturer=Manufacturer(
            name="TestPharma Ltd.",
            address="123 Pharma Road, Mumbai",
            license_no="MH/15/123/2024",
        ),
    )
    defaults.update(overrides)
    return Product(**defaults)


def _make_config(mrp: str = None) -> PackagingConfig:
    product = _make_product()
    blister = BlisterSpec(length=120, width=50, height=8)
    config = PackagingConfig(
        product=product, blister=blister, pack_size="1 x 10", mrp=mrp
    )
    config.carton.calculate_from_blister(blister)
    return config


def _make_complete_artwork(config: PackagingConfig) -> ArtworkSpec:
    """Generate a complete artwork that should pass all checks."""
    return generate_default_artwork(config)


# ---------------------------------------------------------------------------
# Completeness tests
# ---------------------------------------------------------------------------

class TestCompleteness:
    def test_complete_artwork_passes_all(self):
        """A complete artwork generated by the default layout passes."""
        config = _make_config(mrp="₹125.50")
        artwork = _make_complete_artwork(config)
        results = check_completeness(config, artwork)

        failures = [r for r in results if r.status == CheckStatus.FAIL]
        assert len(failures) == 0, (
            f"Unexpected failures: "
            f"{[(r.check_id, r.message) for r in failures]}"
        )

    def test_missing_brand_name_is_critical(self):
        """Missing brand name must be flagged as CRITICAL."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        # Remove all text elements containing the brand name
        artwork.text_elements = [
            el for el in artwork.text_elements
            if config.product.brand_name not in el.content
        ]
        results = check_completeness(config, artwork)

        brand_result = next(r for r in results if r.check_id == "COMP-001")
        assert brand_result.status == CheckStatus.FAIL
        assert brand_result.severity == Severity.CRITICAL

    def test_missing_schedule_h_is_critical(self):
        """Missing Schedule H warning must be CRITICAL."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        # Remove schedule H warning text
        artwork.text_elements = [
            el for el in artwork.text_elements
            if "SCHEDULE H" not in el.content.upper()
        ]
        results = check_completeness(config, artwork)

        schedule_result = next(r for r in results if r.check_id == "COMP-012")
        assert schedule_result.status == CheckStatus.FAIL
        assert schedule_result.severity == Severity.CRITICAL

    def test_missing_mrp_is_major_when_set(self):
        """Missing MRP coding zone is MAJOR when MRP is set in config."""
        config = _make_config(mrp="₹125.50")
        artwork = _make_complete_artwork(config)
        # Remove MRP coding zone
        artwork.coding_zones = [
            cz for cz in artwork.coding_zones
            if "MRP" not in cz.purpose.upper()
        ]
        results = check_completeness(config, artwork)

        mrp_result = next(r for r in results if r.check_id == "COMP-009")
        assert mrp_result.status == CheckStatus.FAIL
        assert mrp_result.severity == Severity.MAJOR

    def test_mrp_not_checked_when_not_set(self):
        """MRP check is skipped when config.mrp is not set."""
        config = _make_config(mrp=None)
        artwork = _make_complete_artwork(config)
        results = check_completeness(config, artwork)

        mrp_results = [r for r in results if r.check_id == "COMP-009"]
        assert len(mrp_results) == 0

    def test_missing_storage_conditions_is_major(self):
        """Missing storage conditions must be MAJOR."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        artwork.text_elements = [
            el for el in artwork.text_elements
            if config.product.storage_conditions not in el.content
        ]
        results = check_completeness(config, artwork)

        storage_result = next(r for r in results if r.check_id == "COMP-013")
        assert storage_result.status == CheckStatus.FAIL
        assert storage_result.severity == Severity.MAJOR

    def test_missing_generic_name_is_critical(self):
        """Missing generic name must be CRITICAL."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        artwork.text_elements = [
            el for el in artwork.text_elements
            if config.product.generic_name not in el.content
        ]
        results = check_completeness(config, artwork)

        generic_result = next(r for r in results if r.check_id == "COMP-002")
        assert generic_result.status == CheckStatus.FAIL
        assert generic_result.severity == Severity.CRITICAL


# ---------------------------------------------------------------------------
# Text comparison tests
# ---------------------------------------------------------------------------

class TestTextCompare:
    def test_exact_match_high_ratio(self):
        """When artwork text matches approved text, ratio should be high."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        # Use the artwork's own text as approved
        approved = " ".join(el.content for el in artwork.text_elements)
        results = compare_text(artwork, approved)

        ratio_result = next(r for r in results if r.check_id == "TEXT-001")
        assert ratio_result.status == CheckStatus.PASS

    def test_missing_text_flagged(self):
        """Missing text from approved source must be flagged."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        # Approved text has extra content not in artwork
        approved = (
            " ".join(el.content for el in artwork.text_elements)
            + " ADDITIONAL MANDATORY REGULATORY TEXT REQUIRED"
        )
        results = compare_text(artwork, approved)

        missing_result = next(r for r in results if r.check_id == "TEXT-002")
        assert missing_result.status == CheckStatus.FAIL
        assert "ADDITIONAL" in missing_result.details

    def test_extra_text_flagged(self):
        """Extra text in artwork not in approved source gets a warning."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        # Use only part of the artwork text as approved
        approved = artwork.text_elements[0].content
        results = compare_text(artwork, approved)

        extra_result = next(r for r in results if r.check_id == "TEXT-003")
        assert extra_result.status == CheckStatus.WARNING


# ---------------------------------------------------------------------------
# Revision comparison tests
# ---------------------------------------------------------------------------

class TestRevisionCompare:
    def test_no_changes_detected(self):
        """Identical artwork versions should report no changes."""
        config = _make_config()
        artwork = _make_complete_artwork(config)
        results = compare_revisions(artwork, artwork)

        assert len(results) == 1
        assert results[0].check_id == "REV-000"
        assert results[0].status == CheckStatus.PASS

    def test_added_element_detected(self):
        """Adding a text element should be detected."""
        config = _make_config()
        old_art = _make_complete_artwork(config)
        new_art = _make_complete_artwork(config)
        new_art.text_elements.append(TextElement(
            id="new-element",
            content="New regulatory text",
            source_field="static",
            panel_type=PanelType.BACK,
            x=5.0, y=120.0,
        ))
        results = compare_revisions(old_art, new_art)

        added = [r for r in results if r.check_id == "REV-001"]
        assert len(added) == 1
        assert "new-element" in added[0].element

    def test_removed_element_detected(self):
        """Removing a text element should be detected."""
        config = _make_config()
        old_art = _make_complete_artwork(config)
        new_art = _make_complete_artwork(config)
        new_art.text_elements = new_art.text_elements[1:]  # Remove first
        results = compare_revisions(old_art, new_art)

        removed = [r for r in results if r.check_id == "REV-002"]
        assert len(removed) == 1

    def test_modified_content_detected(self):
        """Modifying text content should be detected."""
        config = _make_config()
        old_art = _make_complete_artwork(config)
        new_art = _make_complete_artwork(config)
        new_art.text_elements[0].content = "CHANGED BRAND NAME"
        results = compare_revisions(old_art, new_art)

        modified = [r for r in results if r.check_id == "REV-003"]
        assert len(modified) == 1
        assert "CHANGED BRAND NAME" in modified[0].details

    def test_color_change_detected(self):
        """Adding or removing a spot color should be detected."""
        config = _make_config()
        old_art = _make_complete_artwork(config)
        new_art = _make_complete_artwork(config)
        new_art.spot_colors.append(SpotColor(
            name="Pantone 185 C",
            cyan=0, magenta=100, yellow=80, black=0,
        ))
        results = compare_revisions(old_art, new_art)

        color_results = [r for r in results if r.check_id == "REV-010"]
        assert len(color_results) == 1
        assert "Pantone 185 C" in color_results[0].element


# ---------------------------------------------------------------------------
# Barcode validation tests
# ---------------------------------------------------------------------------

class TestBarcodeValidate:
    def test_valid_ean13_passes(self):
        """A valid EAN-13 barcode with correct check digit passes."""
        artwork = ArtworkSpec(
            id="ART-TEST",
            barcodes=[BarcodeElement(
                id="ean13",
                barcode_type=BarcodeType.EAN_13,
                data="4006381333931",  # valid EAN-13
                panel_type=PanelType.BACK,
                x=5.0, y=45.0,
                width=37.29,
                height=25.93,
            )],
        )
        results = validate_barcodes(artwork)

        # All checks should pass
        failures = [r for r in results if r.status == CheckStatus.FAIL]
        assert len(failures) == 0, (
            f"Unexpected failures: "
            f"{[(r.check_id, r.message) for r in failures]}"
        )

    def test_invalid_check_digit_caught(self):
        """EAN-13 with wrong check digit must be flagged."""
        artwork = ArtworkSpec(
            id="ART-TEST",
            barcodes=[BarcodeElement(
                id="ean13-bad",
                barcode_type=BarcodeType.EAN_13,
                data="4006381333932",  # last digit wrong
                panel_type=PanelType.BACK,
                x=5.0, y=45.0,
                width=37.29,
                height=25.93,
            )],
        )
        results = validate_barcodes(artwork)

        check_digit_fail = next(
            r for r in results if r.check_id == "BAR-002"
        )
        assert check_digit_fail.status == CheckStatus.FAIL
        assert check_digit_fail.severity == Severity.CRITICAL

    def test_undersized_barcode_caught(self):
        """Barcode below GS1 minimum dimensions must be flagged."""
        artwork = ArtworkSpec(
            id="ART-TEST",
            barcodes=[BarcodeElement(
                id="ean13-small",
                barcode_type=BarcodeType.EAN_13,
                data="4006381333931",
                panel_type=PanelType.BACK,
                x=5.0, y=45.0,
                width=20.0,   # below 29.83mm minimum
                height=15.0,  # below 22.85mm minimum
            )],
        )
        results = validate_barcodes(artwork)

        width_fail = next(r for r in results if r.check_id == "BAR-003")
        assert width_fail.status == CheckStatus.FAIL

        height_fail = next(r for r in results if r.check_id == "BAR-004")
        assert height_fail.status == CheckStatus.FAIL

    def test_non_digit_data_caught(self):
        """EAN-13 with non-digit data must be flagged."""
        artwork = ArtworkSpec(
            id="ART-TEST",
            barcodes=[BarcodeElement(
                id="ean13-alpha",
                barcode_type=BarcodeType.EAN_13,
                data="40063813ABC31",
                panel_type=PanelType.BACK,
                x=5.0, y=45.0,
                width=37.29,
                height=25.93,
            )],
        )
        results = validate_barcodes(artwork)

        data_fail = next(r for r in results if r.check_id == "BAR-001")
        assert data_fail.status == CheckStatus.FAIL
        assert data_fail.severity == Severity.CRITICAL
